/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsersearchImport } from './routes/usersearch'
import { Route as LikedPostsImport } from './routes/liked-posts'
import { Route as ChatImport } from './routes/chat'
import { Route as IndexImport } from './routes/index'
import { Route as AuserUserIdImport } from './routes/auser.$userId'

// Create/Update Routes

const UsersearchRoute = UsersearchImport.update({
  path: '/usersearch',
  getParentRoute: () => rootRoute,
} as any)

const LikedPostsRoute = LikedPostsImport.update({
  path: '/liked-posts',
  getParentRoute: () => rootRoute,
} as any)

const ChatRoute = ChatImport.update({
  path: '/chat',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuserUserIdRoute = AuserUserIdImport.update({
  path: '/auser/$userId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/chat': {
      preLoaderRoute: typeof ChatImport
      parentRoute: typeof rootRoute
    }
    '/liked-posts': {
      preLoaderRoute: typeof LikedPostsImport
      parentRoute: typeof rootRoute
    }
    '/usersearch': {
      preLoaderRoute: typeof UsersearchImport
      parentRoute: typeof rootRoute
    }
    '/auser/$userId': {
      preLoaderRoute: typeof AuserUserIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ChatRoute,
  LikedPostsRoute,
  UsersearchRoute,
  AuserUserIdRoute,
])

/* prettier-ignore-end */
